
@extends('layouts.master')

@section('content')

  <h2>Ode to a Nightingale</h2>

  <p>by John Keats</p>

  <br>
  <p>
    My&nbsp;heart&nbsp;aches,&nbsp;and&nbsp;a&nbsp;drowsy&nbsp;numbness&nbsp;pains&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;My&nbsp;sense,&nbsp;as&nbsp;though&nbsp;of&nbsp;hemlock&nbsp;I&nbsp;had&nbsp;drunk,&nbsp;<br>
    Or&nbsp;emptied&nbsp;some&nbsp;dull&nbsp;opiate&nbsp;to&nbsp;the&nbsp;drains&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;One&nbsp;minute&nbsp;past,&nbsp;and&nbsp;Lethe-wards&nbsp;had&nbsp;sunk:&nbsp;<br>
    'Tis&nbsp;not&nbsp;through&nbsp;envy&nbsp;of&nbsp;thy&nbsp;happy&nbsp;lot,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But&nbsp;being&nbsp;too&nbsp;happy&nbsp;in&nbsp;thine&nbsp;happiness,—&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That&nbsp;thou,&nbsp;light-winged&nbsp;Dryad&nbsp;of&nbsp;the&nbsp;trees&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In&nbsp;some&nbsp;melodious&nbsp;plot&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Of&nbsp;beechen&nbsp;green,&nbsp;and&nbsp;shadows&nbsp;numberless,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Singest&nbsp;of&nbsp;summer&nbsp;in&nbsp;full-throated&nbsp;ease.&nbsp;<br>
    <br>
    O,&nbsp;for&nbsp;a&nbsp;draught&nbsp;of&nbsp;vintage!&nbsp;that&nbsp;hath&nbsp;been&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cool'd&nbsp;a&nbsp;long&nbsp;age&nbsp;in&nbsp;the&nbsp;deep-delved&nbsp;earth,&nbsp;<br>
    Tasting&nbsp;of&nbsp;Flora&nbsp;and&nbsp;the&nbsp;country&nbsp;green,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Dance,&nbsp;and&nbsp;Provençal&nbsp;song,&nbsp;and&nbsp;sunburnt&nbsp;mirth!&nbsp;<br>
    O&nbsp;for&nbsp;a&nbsp;beaker&nbsp;full&nbsp;of&nbsp;the&nbsp;warm&nbsp;South,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Full&nbsp;of&nbsp;the&nbsp;true,&nbsp;the&nbsp;blushful&nbsp;Hippocrene,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;With&nbsp;beaded&nbsp;bubbles&nbsp;winking&nbsp;at&nbsp;the&nbsp;brim,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And&nbsp;purple-stained&nbsp;mouth;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;That&nbsp;I&nbsp;might&nbsp;drink,&nbsp;and&nbsp;leave&nbsp;the&nbsp;world&nbsp;unseen,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And&nbsp;with&nbsp;thee&nbsp;fade&nbsp;away&nbsp;into&nbsp;the&nbsp;forest&nbsp;dim:&nbsp;<br>
    <br>
    Fade&nbsp;far&nbsp;away,&nbsp;dissolve,&nbsp;and&nbsp;quite&nbsp;forget&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;What&nbsp;thou&nbsp;among&nbsp;the&nbsp;leaves&nbsp;hast&nbsp;never&nbsp;known,&nbsp;<br>
    The&nbsp;weariness,&nbsp;the&nbsp;fever,&nbsp;and&nbsp;the&nbsp;fret&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Here,&nbsp;where&nbsp;men&nbsp;sit&nbsp;and&nbsp;hear&nbsp;each&nbsp;other&nbsp;groan;&nbsp;<br>
    Where&nbsp;palsy&nbsp;shakes&nbsp;a&nbsp;few,&nbsp;sad,&nbsp;last&nbsp;gray&nbsp;hairs,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Where&nbsp;youth&nbsp;grows&nbsp;pale,&nbsp;and&nbsp;spectre-thin,&nbsp;and&nbsp;dies;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Where&nbsp;but&nbsp;to&nbsp;think&nbsp;is&nbsp;to&nbsp;be&nbsp;full&nbsp;of&nbsp;sorrow&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And&nbsp;leaden-eyed&nbsp;despairs,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Where&nbsp;Beauty&nbsp;cannot&nbsp;keep&nbsp;her&nbsp;lustrous&nbsp;eyes,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Or&nbsp;new&nbsp;Love&nbsp;pine&nbsp;at&nbsp;them&nbsp;beyond&nbsp;to-morrow.&nbsp;<br>
    <br>
    Away!&nbsp;away!&nbsp;for&nbsp;I&nbsp;will&nbsp;fly&nbsp;to&nbsp;thee,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Not&nbsp;charioted&nbsp;by&nbsp;Bacchus&nbsp;and&nbsp;his&nbsp;pards,&nbsp;<br>
    But&nbsp;on&nbsp;the&nbsp;viewless&nbsp;wings&nbsp;of&nbsp;Poesy,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Though&nbsp;the&nbsp;dull&nbsp;brain&nbsp;perplexes&nbsp;and&nbsp;retards:&nbsp;<br>
    Already&nbsp;with&nbsp;thee!&nbsp;tender&nbsp;is&nbsp;the&nbsp;night,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And&nbsp;haply&nbsp;the&nbsp;Queen-Moon&nbsp;is&nbsp;on&nbsp;her&nbsp;throne,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cluster'd&nbsp;around&nbsp;by&nbsp;all&nbsp;her&nbsp;starry&nbsp;Fays;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;But&nbsp;here&nbsp;there&nbsp;is&nbsp;no&nbsp;light,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;what&nbsp;from&nbsp;heaven&nbsp;is&nbsp;with&nbsp;the&nbsp;breezes&nbsp;blown&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Through&nbsp;verdurous&nbsp;glooms&nbsp;and&nbsp;winding&nbsp;mossy&nbsp;ways.&nbsp;<br>
    <br>
    I&nbsp;cannot&nbsp;see&nbsp;what&nbsp;flowers&nbsp;are&nbsp;at&nbsp;my&nbsp;feet,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nor&nbsp;what&nbsp;soft&nbsp;incense&nbsp;hangs&nbsp;upon&nbsp;the&nbsp;boughs,&nbsp;<br>
    But,&nbsp;in&nbsp;embalmed&nbsp;darkness,&nbsp;guess&nbsp;each&nbsp;sweet&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Wherewith&nbsp;the&nbsp;seasonable&nbsp;month&nbsp;endows&nbsp;<br>
    The&nbsp;grass,&nbsp;the&nbsp;thicket,&nbsp;and&nbsp;the&nbsp;fruit-tree&nbsp;wild;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;White&nbsp;hawthorn,&nbsp;and&nbsp;the&nbsp;pastoral&nbsp;eglantine;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fast&nbsp;fading&nbsp;violets&nbsp;cover'd&nbsp;up&nbsp;in&nbsp;leaves;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;And&nbsp;mid-May's&nbsp;eldest&nbsp;child,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The&nbsp;coming&nbsp;musk-rose,&nbsp;full&nbsp;of&nbsp;dewy&nbsp;wine,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The&nbsp;murmurous&nbsp;haunt&nbsp;of&nbsp;flies&nbsp;on&nbsp;summer&nbsp;eves.&nbsp;<br>
    <br>
    Darkling&nbsp;I&nbsp;listen;&nbsp;and,&nbsp;for&nbsp;many&nbsp;a&nbsp;time&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I&nbsp;have&nbsp;been&nbsp;half&nbsp;in&nbsp;love&nbsp;with&nbsp;easeful&nbsp;Death,&nbsp;<br>
    Call'd&nbsp;him&nbsp;soft&nbsp;names&nbsp;in&nbsp;many&nbsp;a&nbsp;mused&nbsp;rhyme,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To&nbsp;take&nbsp;into&nbsp;the&nbsp;air&nbsp;my&nbsp;quiet&nbsp;breath;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now&nbsp;more&nbsp;than&nbsp;ever&nbsp;seems&nbsp;it&nbsp;rich&nbsp;to&nbsp;die,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To&nbsp;cease&nbsp;upon&nbsp;the&nbsp;midnight&nbsp;with&nbsp;no&nbsp;pain,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;While&nbsp;thou&nbsp;art&nbsp;pouring&nbsp;forth&nbsp;thy&nbsp;soul&nbsp;abroad&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In&nbsp;such&nbsp;an&nbsp;ecstasy!&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Still&nbsp;wouldst&nbsp;thou&nbsp;sing,&nbsp;and&nbsp;I&nbsp;have&nbsp;ears&nbsp;in&nbsp;vain—&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To&nbsp;thy&nbsp;high&nbsp;requiem&nbsp;become&nbsp;a&nbsp;sod.&nbsp;<br>
    <br>
    Thou&nbsp;wast&nbsp;not&nbsp;born&nbsp;for&nbsp;death,&nbsp;immortal&nbsp;Bird!&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No&nbsp;hungry&nbsp;generations&nbsp;tread&nbsp;thee&nbsp;down;&nbsp;<br>
    The&nbsp;voice&nbsp;I&nbsp;hear&nbsp;this&nbsp;passing&nbsp;night&nbsp;was&nbsp;heard&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In&nbsp;ancient&nbsp;days&nbsp;by&nbsp;emperor&nbsp;and&nbsp;clown:&nbsp;<br>
    Perhaps&nbsp;the&nbsp;self-same&nbsp;song&nbsp;that&nbsp;found&nbsp;a&nbsp;path&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Through&nbsp;the&nbsp;sad&nbsp;heart&nbsp;of&nbsp;Ruth,&nbsp;when,&nbsp;sick&nbsp;for&nbsp;home,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;She&nbsp;stood&nbsp;in&nbsp;tears&nbsp;amid&nbsp;the&nbsp;alien&nbsp;corn;&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The&nbsp;same&nbsp;that&nbsp;oft-times&nbsp;hath&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Charm'd&nbsp;magic&nbsp;casements,&nbsp;opening&nbsp;on&nbsp;the&nbsp;foam&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Of&nbsp;perilous&nbsp;seas,&nbsp;in&nbsp;faery&nbsp;lands&nbsp;forlorn.&nbsp;<br>
    <br>
    Forlorn!&nbsp;the&nbsp;very&nbsp;word&nbsp;is&nbsp;like&nbsp;a&nbsp;bell&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;To&nbsp;toll&nbsp;me&nbsp;back&nbsp;from&nbsp;thee&nbsp;to&nbsp;my&nbsp;sole&nbsp;self!&nbsp;<br>
    Adieu!&nbsp;the&nbsp;fancy&nbsp;cannot&nbsp;cheat&nbsp;so&nbsp;well&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;As&nbsp;she&nbsp;is&nbsp;fam'd&nbsp;to&nbsp;do,&nbsp;deceiving&nbsp;elf.&nbsp;<br>
    Adieu!&nbsp;adieu!&nbsp;thy&nbsp;plaintive&nbsp;anthem&nbsp;fades&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Past&nbsp;the&nbsp;near&nbsp;meadows,&nbsp;over&nbsp;the&nbsp;still&nbsp;stream,&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Up&nbsp;the&nbsp;hill-side;&nbsp;and&nbsp;now&nbsp;'tis&nbsp;buried&nbsp;deep&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;In&nbsp;the&nbsp;next&nbsp;valley-glades:&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Was&nbsp;it&nbsp;a&nbsp;vision,&nbsp;or&nbsp;a&nbsp;waking&nbsp;dream?&nbsp;<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fled&nbsp;is&nbsp;that&nbsp;music:—Do&nbsp;I&nbsp;wake&nbsp;or&nbsp;sleep?
  </p>

@endsection